// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzxkNdoyj_DTpHQQ744Ai1dkwIaOTnFIE',
    appId: '1:290112471776:web:7eb4091b1c98fe7a62c685',
    messagingSenderId: '290112471776',
    projectId: 'machinetest-a98cd',
    authDomain: 'machinetest-a98cd.firebaseapp.com',
    storageBucket: 'machinetest-a98cd.appspot.com',
    measurementId: 'G-2NQRN13LEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0DDjpUIeCfC38ARWcP-30L61UfTiR8yI',
    appId: '1:290112471776:android:5dd23e7fb04a3c3062c685',
    messagingSenderId: '290112471776',
    projectId: 'machinetest-a98cd',
    storageBucket: 'machinetest-a98cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC_zynK5zJ1KMCF0Kv8n6TyslC5anJ9wE',
    appId: '1:290112471776:ios:537c5982e4ab28e162c685',
    messagingSenderId: '290112471776',
    projectId: 'machinetest-a98cd',
    storageBucket: 'machinetest-a98cd.appspot.com',
    iosBundleId: 'com.example.machinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC_zynK5zJ1KMCF0Kv8n6TyslC5anJ9wE',
    appId: '1:290112471776:ios:768e4199a5506db662c685',
    messagingSenderId: '290112471776',
    projectId: 'machinetest-a98cd',
    storageBucket: 'machinetest-a98cd.appspot.com',
    iosBundleId: 'com.example.machinetest.RunnerTests',
  );
}
